apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: familtyapp
build:
  artifacts:
  - image: familyapp/auth
    context: auth
    sync:
      manual:
        - src: src/**/*.ts
          dest: .
deploy:
  statusCheckDeadlineSeconds: 180
  kubectl:
    manifests:
     - infra/k8s/auth/*
     - infra/k8s/k8-dev/*
