apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: familyapp
build:
  artifacts:
    - image: familyapp/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: familyapp/shopping
      context: shopping
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: familyapp/client
      context: client
      sync:
        manual:
          - src: src/**/*.tsx
            dest: .
          - src: src/**/*.ts
            dest: .
deploy:
  statusCheckDeadlineSeconds: 180
  kubectl:
    manifests:
      - infra/k8s/auth/*
      - infra/k8s/client/*
      - infra/k8s/shopping/*
      - infra/k8s/k8-dev/*
