apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-mongo
  template:
    metadata:
      labels:
        app: shopping-mongo
    spec:
      containers:
        - name: shopping-mongo
          image: mongo
