apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-mongo
  template:
    metadata:
      labels:
        app: group-mongo
    spec:
      containers:
        - name: group-mongo
          image: mongo
